name: Build and Deploy ASP.NET Core ChatClube with PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Detectar versão do SDK do global.json
        id: set_version
        run: |
          VERSION=$(jq -r .sdk.version global.json)
          echo "sdk_version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ steps.set_version.outputs.sdk_version }}

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar
        run: dotnet build --no-restore

      - name: Publicar
        run: dotnet publish -c Release -o ./publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app

      - name: Login com identidade gerenciada do Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy para Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'anderson' # nome exato do seu Web App no Azure
          package: .
