steps:
  - name: Checkout
    uses: actions/checkout@v3

  - name: Setup .NET
    uses: actions/setup-dotnet@v4
    with:
      dotnet-version: '9.0.100-preview.3'

  - name: Restore
    run: dotnet restore

  - name: Build
    run: dotnet build -c Release

  - name: Publish
    run: dotnet publish -c Release -o ./publish

  - name: Upload artifact
    uses: actions/upload-artifact@v4
    with:
      name: app
      path: ./publish
