# Docs: https://github.com/Azure/webapps-deploy
# Ação oficial do Azure para .NET + GitHub Actions

name: Build and deploy ASP.Net Core app to Azure Web App - anderson

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependências
        run: dotnet restore

      - name: Build com Release
        run: dotnet build --configuration Release --no-restore

      - name: Publicar o app
        run: dotnet publish -c Release -o ./publish

      - name: Upload do artifact para deploy
        uses: actions/upload-artifact@v4
        with:
          name: app-publish
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Baixar artifact
        uses: actions/download-artifact@v4
        with:
          name: app-publish

      - name: Login no Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B6DC6BC2841F45E9AEA71EC63E8FEABF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9C5F8B4543CD4E8784592067A0559FE3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_856A840FB24E4E5695B982090F3293A6 }}

      - name: Deploy no Azure App Service
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'anderson'
          slot-name: 'Production'
          package: .
