name: Build and Deploy ASP.NET Core ChatClube (.NET 9 + Managed Identity)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup .NET 9 Preview
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar projeto
        run: dotnet build --no-restore --configuration Release

      - name: Publicar projeto
        run: dotnet publish -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write     # necessário para login com Managed Identity
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: ./publish

      - name: Login com Azure usando Managed Identity
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-managed-identity: true
          allow-no-subscriptions: true

      - name: Deploy para Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'chatclube'  # substitua pelo nome do seu Web App real
          package: ./publish
