name: Gerar e Postar Meme no Facebook
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 14 * * *'
jobs:
  gerar-e-postar:
    runs-on: ubuntu-latest
    environment: Facebook
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Instalar dependências
        run: npm install
      - name: Gerar Meme e Postar no Facebook
        run: node scripts/generate-meme.js
        env:
          PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}
          FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
